spring.data.mongodb.uri=mongodb+srv://srushtikansara06_db_user:cravelt2026@m0-free-cluster.cyug4zj.mongodb.net/cravelt?appName=M0-FREE-Clusterspring.data.mongodb.uri=mongodb+srv://srushtikansara06_db_user:cravelt2026@m0-free-cluster.cyug4zj.mongodb.net/cravelt?retryWrites=true&w=majority&appName=M0-FREE-Cluster
server.port=10000
server.address=0.0.0.0
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cravelt26@gmail.com
spring.mail.password=jupy bhjn oayq twzc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true