
server.port=9999


spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb+srv://srushtikansara06_db_user:LouXgr9yg4l22zml@m0-free-cluster.cyug4zj.mongodb.net/cravelt?retryWrites=true&w=majority&appName=M0-FREE-Cluster
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=snk2603@gmail.com
spring.mail.password=jupy bhjn oayq twzc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true