spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:10000}
server.address=0.0.0.0

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=cravelt26@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true